#!/bin/bash

#fslroi bedpostx/data.nii.gz b0.nii.gz 0 1
#fslmaths b0.nii.gz -mas bedpostx/nodif_brain_mask.nii.gz b0_brain.nii.gz
#mri_convert ../flair/Flair_brain.nii.gz -vs 2 2 2 ../flair/Flair_brain_2mm.nii.gz
#mri_convert ../flair/Flair_wmh_mask.nii.gz -vs 2 2 2 ../flair/Flair_wmh_mask_2mm.nii.gz
#fslmaths Flair_wmh_mask_2mm.nii.gz -thr .9 -bin Flair_wmh_mask_2mm.nii.gz
#flirt -in b0_brain.nii.gz -ref ../flair/Flair_brain_2mm.nii.gz -out b0toFlair.nii.gz -omat b0toflair.mat

mri_convert ../flair/Flair_brain.nii.gz -vs 2 2 2 Flair_brain_2mm.nii.gz
mri_convert ../flair/Flair_wmh_mask.nii.gz -vs 2 2 2 Flair_wmh_mask_2mm.nii.gz
/usr/local/ANTs-2.1.0-rc3/bin/antsIntroduction.sh -d 3 -i ../flair/Flair_brain_2mm.nii.gz -m 30x90x20 -o Flair_2mm_to_MNI_2mm -s CC -r /usr/share/fsl/5.0/data/standard/MNI152_T1_2mm_brain.nii.gz -t GR
/usr/local/ANTs-2.1.0-rc3/bin/WarpImageMultiTransform 3 ../flair/Flair_wmh_mask_2mm.nii.gz Flair_wmh_mask_2mmMNI.nii.gz  -R /usr/share/fsl/5.0/data/standard/MNI152_T1_2mm_brain.nii.gz \
/usr/share/fsl/5.0/data/standard/MNI152_T1_2mm_brain.nii.gz Flair_2mm_to_MNI_2mmAffine.txt 

mri_convert T1.nii.gz -vs 2 2 2 T1_2mm.nii.gz
mv FA.nii.gz FA_old.nii.gz
cp dtifit/DTI_FA.nii.gz FA.nii.gz
flirt -in FA.nii.gz -ref T1_2mm.nii.gz -omat FA2T1_2mm.mat -out FA2T1_2mm.nii.gz
c3d_affine_tool -ref T1_2mm.nii.gz -src FA.nii.gz FA2T1_2mm.mat -fsl2ras -oitk FA2T1_2mm.txt
export ANTSPATH=/usr/local/ANTs-2.1.0-rc3/bin/
/usr/local/ANTs-2.1.0-rc3/bin/antsIntroduction.sh -d 3 -i T1_2mm.nii.gz -m 30x90x20 -o T1_2mm_to_MNI_2mm -s CC -r /usr/share/fsl/5.0/data/standard/MNI152_T1_2mm_brain.nii.gz -t GR
/usr/local/ANTs-2.1.0-rc3/bin/WarpImageMultiTransform 3 FA.nii.gz FA_to_MNI2mm_deformed.nii.gz  -R /usr/share/fsl/5.0/data/standard/MNI152_T1_2mm_brain.nii.gz \ 					T1_2mm_to_MNI_2mmWarp.nii.gz T1_2mm_to_MNI_2mmAffine.txt FA2T1_2mm.nii.gz FA2T1_2mm.txt	 
